language: go
go_import_path: github.com/jhunters/timewheel

sudo: false

go:
- 1.13

before_install:
- go get -v honnef.co/go/tools/...
- go get -v github.com/kisielk/errcheck

script:
- make test
- make race
# - make errcheck

after_success:
- bash <(curl -s https://codecov.io/bash)